spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    mail:
      host: ${MAIL_HOST:localhost}
      port: ${MAIL_PORT:1025}

notification:
  email:
    from: ${NOTIFICATION_EMAIL_FROM:noreply@vendaplanejada.com.br}